version: "3.5"
services:
  wildfly:
    build:
      context: .
      dockerfile: ./docker-wildfly/Dockerfile
    network_mode: "host"
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - "postgresql"

  postgresql:
    image: postgres:14.5-alpine
    network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local

